name: dbui

volumes:
  db:

services:
  client:
    image: ghcr.io/aurer/dbui-client:latest
    container_name: dbui-client
    ports:
      - ${CLIENT_PORT:-4080}:80
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy
  api:
    image: ghcr.io/aurer/dbui-api:latest
    container_name: dbui-api
    ports:
      - 4000:4000
    environment:
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: dbui
      DB_URL: db:3306
      API_URL: 0.0.0.0:4000
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:4000"]
      interval: 5s
      timeout: 3s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mariadb:11.2
    container_name: dbui-db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mariadb -u root -p${DB_PASSWORD} dbui -e 'SELECT CURRENT_TIMESTAMP' || exit 1"
        ]
      interval: 5s
      timeout: 3s
      retries: 3
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: dbui
    volumes:
      - db:/var/lib/mysql
